FROM python:3

WORKDIR /app




RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    chromium \
    chromium-driver && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
ENV PYTHONUNBUFFERED=1 \
    PORT=8000 



CMD ["python","raspa.py"]